// React/ReactNode/src/App.tsx
import * as React from "react";
import { BrowserRouter as Router, Route, Link } from "react-router-dom";

import { FirstPage, SecondPage } from "./Components";
import { AppSettings } from "./Services";

import "./App.css";

export class App extends React.Component<any, any>
{
    appSettings = AppSettings.Load();

    render(): JSX.Element
    {
        return (
            <Router>
                <div>
                    <header>
                        <h1>React Template</h1>
                        <Link to={`${this.appSettings.rootUrl}`}>Home</Link>
                        <Link to={`${this.appSettings.rootUrl}second`}>Second</Link>
                    </header>
                    <section>
                        <Route exact path={`${this.appSettings.rootUrl}`} component={FirstPage}/>
                        <Route path={`${this.appSettings.rootUrl}second`} component={SecondPage}/>
                    </section>
                </div>
            </Router>
        );
    }
};

// Angular/AngularNode/src/App.ts
import { Component } from "@angular/core";

import { AppSettings } from "./Services";

const template = `
    <header>
        <h2>Angular  Template</h2>
        <div id="header-links">
            <a routerLink="/">Home</a>
            <a routerLink="/second">Second</a>
        </div>
        <div id="header-version">{{appSettings.version}}</div>
    </header>
    <section>
        <router-outlet></router-outlet>
    </section>
`;
//const styles = [require("./App.css").toString()];

@Component({
    moduleId: module.id,
    selector: "app",
    template: template,
    //styles: styles
    styleUrls: ["App.css"]
})
export class App {
    constructor(private appSettings: AppSettings) { }
}
